version: '3.8'

services:
    db:
        image: mysql:8.0
        container_name: mysql
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
            MYSQL_DATABASE: ${DB_NAME}
            MYSQL_USER: ${DB_USER}
            MYSQL_PASSWORD: ${DB_PASSWORD}
        volumes:
            - db_data:/var/lib/mysql
            - ./initdb.sql:/docker-entrypoint-initdb.d/initdb.sql
        networks:
            - app-network

    app:
        build: .
        container_name: node-app
        env_file:
            - .env
        ports:
            - '3000:3000'
        depends_on:
            - db
        networks:
            - app-network
        volumes:
            - .:/usr/src/app
            - /usr/src/app/node_modules
        entrypoint: /bin/bash -c "while !</dev/tcp/db/3306; do sleep 1; done; npm start"

networks:
    app-network:
        driver: bridge

volumes:
    db_data:
